### ISSUE TITLE
Variable names

### ISSUE THREAD

**Issue by OrDuan** [idoed/InterviewProject#22]
https://github.com/idoed/InterviewProject/blob/67c45504a926ea305f0bedae5a5ee6799886b898/HandlingCalls/src/com/company/SupportPanel.java#L15

Think about someone who doesn't know your code when you think about variable names, num1 num2 doesn't means anything and I have to check the reset of the code to understand it. In general, when you should never call variables things like 

`x`, `y`, `s`, `mNum1`, `mNum2`, `temp`, `myXXX` etc...

The corresponding good naming to that list:

`posX`, `posY`, `orderSummery`, `employeesLevelOne`, `employeesLevelTwo`, `tempLocation`, `supportManager`(Instance of `**S**upportManager`, P.S Nir choose this name which is probably better than my `SupportPanel`)

**Comment by OrDuan** [comment]
@nirdev did I do the Java style right?

**Comment by nirdev** [comment]
yes

**Comment by idoed** [comment]
done
