### ISSUE TITLE
One queue

### ISSUE THREAD

**Issue by OrDuan** [idoed/InterviewProject#23]
https://github.com/idoed/InterviewProject/blob/67c45504a926ea305f0bedae5a5ee6799886b898/HandlingCalls/src/com/company/SupportPanel.java#L17-L18

It's much better to have one queue, that you'll add to the end of it(coming out first) instead of another queue. 

When you'll have one queue, you also have to add `level` to the `Call` class and when you allocate the calls, check the call's level

**Comment by idoed** [comment]
how important it is? because i chacked on web (short time i have to say) but i couldnt find how to to add object on the top of the queue. btw Call object doesnt have Level param. it only holds id and Boolean Solved

**Comment by OrDuan** [comment]
It's kinda important because I guess that what they wanted to see - that you planned it right, here is what I found:

https://docs.oracle.com/javase/7/docs/api/java/util/Deque.html

> A linear collection that supports element insertion and removal at both ends. The name deque is short for "double ended queue"

I'm sure Nir can help with the implemention and it's always nice to learn new collection types.

You will have to implement a `level` for each call because if you use the `deque`, you'll have only one queue, and you won't know if the next `call` is level one or level two(that came back to the queue).

Call me if that still isn't clear

**Comment by idoed** [comment]
done

**Comment by idoed** [comment]
done
