### ISSUE TITLE
Style guild

### ISSUE THREAD

**Issue by OrDuan** [idoed/InterviewProject#24]
https://github.com/idoed/InterviewProject/blob/master/HandlingCalls/src/com/company/SupportPanel.java#L63-L66

I know this is looks like a stupid and small thing, and I agree :) but people judge you by the code style, it's easy to see you're new dev when you don't clean up the spaces near the `=` signs. Doesn't your IDE show you that? @nirdev - any tool? plugin?

As I said, it looks stupid thing, but developers with experience just doesn't write in inconsistent style.

That being said, stick to one convention, when declaring variables, spaces, comments structure, doc strings. Other anti-style things I found:

Spaces:
https://github.com/idoed/InterviewProject/blob/master/HandlingCalls/src/com/company/SupportPanel.java#L41

https://github.com/idoed/InterviewProject/blob/master/HandlingCalls/src/com/company/SupportPanel.java#L49-L52
vs
https://github.com/idoed/InterviewProject/blob/master/HandlingCalls/src/com/company/SupportPanel.java#L32

Indention:
https://github.com/idoed/InterviewProject/blob/master/HandlingCalls/src/com/company/SupportPanel.java#L88

No explanation what is the param:
https://github.com/idoed/InterviewProject/blob/master/HandlingCalls/src/com/company/SupportPanel.java#L51

**Comment by nirdev** [comment]
https://stackoverflow.com/a/16580200/6028746

**Comment by idoed** [comment]
Thats learnd me 1 or 2 things, thanks, done
