### ISSUE TITLE
README

### ISSUE THREAD

**Issue by OrDuan** [idoed/InterviewProject#26]
## Introduction 
This project demonstrate a support call center. There are 3 types of groups:
- Level 1 employees
- Level 2 employees
- The manager

When a new call received, a level 1 will handle it, If level 1 can't solve the problem/busy the call goes to level 2 employees, if they cant solve the problem it goes to the manager if level 2 employees are all busy, the call goes to a waiting list.

## Structure 
I created 2 model classes: `Employee` and `Call` which are the representation of the employees and calls from the above paragraph. 
In addition, I wrote a singleton `SupportPanel` class where I keep the state of the support center and manage state changes like adding a call to the queue/check who can handle it.

**Comment by OrDuan** [comment]
Markup:
```
## Introduction 
This project demonstrate a support call center. There are 3 types of groups:
- Level 1 employees
- Level 2 employees
- The manager

When a new call received, a level 1 will handle it, If level 1 can't solve the problem/busy the call goes to level 2 employees, if they cant solve the problem it goes to the manager if level 2 employees are all busy, the call goes to a waiting list.

## Structure 
I created 2 model classes: `Employee` and `Call` which are the representation of the employees and calls from the above paragraph. 
In addition, I wrote a singleton `SupportPanel` class where I keep the state of the support center and manage state changes like adding a call to the queue/check who can handle it.
```

**Comment by idoed** [comment]
done
