### ISSUE TITLE
use the /**/ "comment section" to write long comments, also the comment here and below are not written well

### ISSUE THREAD

**Issue by nirdev** [idoed/InterviewProject#8]
https://github.com/idoed/InterviewProject/blob/d556f36191f7271be7a9c106aac2f22a1e16cf2b/HandlingCalls/src/com/company/SupportPanel.java#L79

**Comment by idoed** [comment]
i made a change ill let u see the diff.. because there's not UI i show the 2 options for taking a call, case that the problem get solved by the second team and than by the manager if not.

**Comment by idoed** [comment]
done
